name: Check and Build Tailscale-lite New Version

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # 每周检查一次（周日凌晨）

jobs:
  check-tailscale-version:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.set_output.outputs.latest_version }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest Tailscale version
      id: get_version
      run: |
        latest_version=$(curl -s https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r .tag_name)
        echo "latest_version=$latest_version" >> $GITHUB_ENV

    - name: Set output
      id: set_output
      run: echo "::set-output name=latest_version::${{ env.latest_version }}"

    - name: Store latest version in a file
      run: echo "${{ env.latest_version }}" > latest_version.txt

    - name: Commit latest version if changed
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add latest_version.txt
          git commit -m "Update latest Tailscale version to ${{ env.latest_version }}"
          git push
        else
          echo "No changes in the latest version."
        fi

  build-tailscale:
    needs: check-tailscale-version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read current version
      id: read_version
      run: |
        CURRENT_VERSION=$(cat latest_version.txt)
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: sudo apt-get install -y upx

    - name: Clone Tailscale repository
      run: git clone https://github.com/tailscale/tailscale

    - name: Set VERSION_SHORT environment variable
      run: echo "VERSION_SHORT=${{ env.CURRENT_VERSION }}" >> $GITHUB_ENV

    - name: Build Small Tailscale Binary
      run: |
        cd tailscale
        ./build_dist.sh --extra-small
        # Compress the binaries using upx
        upx --best --lzma ./cmd/tailscaled/tailscaled
        upx --best --lzma ./cmd/tailscale/tailscale
        # Verify the binary size
        ls -lh ./cmd/tailscaled/tailscaled
        ls -lh ./cmd/tailscale/tailscale

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: small-tailscaled
        path: tailscale/cmd/tailscaled/tailscaled

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: small-tailscale
        path: tailscale/cmd/tailscale/tailscale
